# Generated by Django 4.2.1 on 2023-08-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0018_auto_20201015_2036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
